source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

# Replace `<Your Target Name>` with your app's target name.
target 'Convey' do
  pod 'Alamofire', '~> 4.7.2'
  pod 'PusherChatkit', '~> 0.8.2'
  pod 'MessageKit', '~> 1.0.0'
end
