source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

# Replace `<Your Target Name>` with your app's target name.
target 'Convey' do
  pod 'Alamofire', '~> 4.7.3'
  pod 'PusherChatkit', '~> 0.8.4'
  pod 'MessageKit', '~> 1.0.0'
  pod 'NotificationBannerSwift', '~> 1.6.3'
  pod 'PushNotifications', '~> 1.0.1'
end
